name: UPM on npsjs.com
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: actions/setup-node@v4
      with:
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish
      working-directory: Packages/com.github.asus4.onnxruntime
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    - run: npm publish
      working-directory: Packages/com.github.asus4.onnxruntime.unity
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
